version: '3.8'

services:
  client:
    container_name: steamless-donation_frontend
    image: steamless-donation-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/node-app
      # - /usr/node-app/node_modules
    restart: unless-stopped
    # command: npm run start
